@startuml

title "calc関数とapplyUsePoint関数の流れ"

|calc|

start

:dividePointsByTypeを呼び出してポイントを4タイプに分ける;

:2つの使用ポイントの配列と2つの獲得ポイント計４つあるのを\nそれぞれまとめて2つにする;

repeat

:獲得ポイントの配列に対してapplyUsePoint関数を呼び出す;

|applyUsePoint|

:paymentActionLoop関数を呼び出す;

|paymentActionLoop|

:呼び出される;

|applyUsePoint|

:処理する;

|calc|

repeat while(使用ポイントのすべての値を処理するまで)

|calc|

:使用ポイントと獲得ポイントを1つにまとめて返す;
stop

@enduml