@startuml

title "許容できるポイント計算の構造"

:通常ポイントと限定ポイントを切り分ける;

fork 

:限定ポイントの配列の中身を計算させる;

:残ポイントを出す;

fork again

:通常ポイントの配列の中身を計算させる;

:残ポイントを出す;

end fork

:通常ポイントと期間限定ポイントの残ポイントを\nオブジェクトにして返す;

@enduml